import { PrismaClient, Role, UserStatus, EventStatus, EventMode } from '@prisma/client';
import bcrypt from 'bcrypt';

const prisma = new PrismaClient();

const mockUsersData = [
  { id: "usr-001", name: "Rahim Uddin", email: "rahim@example.com", role: Role.USER, verified: true, status: UserStatus.ACTIVE, createdAt: new Date("2025-01-10") },
  { id: "usr-002", name: "Sadia Islam", email: "sadia@example.com", role: Role.ORGANIZER, verified: true, status: UserStatus.ACTIVE, createdAt: new Date("2025-02-14") },
  { id: "usr-003", name: "Tanvir Ahmed", email: "tanvir@example.com", role: Role.USER, verified: false, status: UserStatus.ACTIVE, createdAt: new Date("2025-03-05") },
  { id: "usr-004", name: "Nusrat Jahan", email: "nusrat@example.com", role: Role.ORGANIZER, verified: true, status: UserStatus.ACTIVE, createdAt: new Date("2025-03-22") },
  { id: "usr-005", name: "Arif Hossain", email: "arif@example.com", role: Role.USER, verified: true, status: UserStatus.SUSPENDED, createdAt: new Date("2025-04-01") },
  { id: "usr-006", name: "Fahmida Akter", email: "fahmida@example.com", role: Role.USER, verified: false, status: UserStatus.ACTIVE, createdAt: new Date("2025-04-18") },
  { id: "usr-007", name: "Mehedi Hassan", email: "mehedi@example.com", role: Role.ORGANIZER, verified: true, status: UserStatus.ACTIVE, createdAt: new Date("2025-05-09") },
  { id: "usr-008", name: "Sumaiya Begum", email: "sumaiya@example.com", role: Role.USER, verified: true, status: UserStatus.ACTIVE, createdAt: new Date("2025-05-30") },
  { id: "usr-009", name: "Khaled Mahmud", email: "khaled@example.com", role: Role.ORGANIZER, verified: false, status: UserStatus.SUSPENDED, createdAt: new Date("2025-06-12") },
  { id: "usr-010", name: "Riya Chakraborty", email: "riya@example.com", role: Role.USER, verified: true, status: UserStatus.ACTIVE, createdAt: new Date("2025-07-04") },
  { id: "usr-011", name: "Imran Karim", email: "imran@example.com", role: Role.USER, verified: false, status: UserStatus.ACTIVE, createdAt: new Date("2025-07-19") },
  { id: "usr-012", name: "Tasnim Rahman", email: "tasnim@example.com", role: Role.ORGANIZER, verified: true, status: UserStatus.ACTIVE, createdAt: new Date("2025-08-01") },
];

function daysFromNow(days: number): Date {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d;
}

const mockEventsRaw = [
  {
    name: "CUET Innovation Hackathon 2026",
    category: "Hackathon",
    organizerName: "CSE Club, CUET",
    eventDate: daysFromNow(20),
    eventTime: "9:00 AM",
    venue: "CUET Auditorium",
    city: "Chattogram",
    mode: EventMode.OFFLINE,
    registrationDeadline: daysFromNow(3),
    registrationFee: "৳300 per team",
    prizePool: "৳150,000",
    eligibility: "Undergraduate students, teams of 3-4",
    teamSize: "3-4 members",
    availableSeats: 120,
    certificateInfo: "E-certificate for all participants, printed certificate for winners",
    description: "A 24-hour hackathon focused on building solutions for campus and civic problems using any tech stack.",
    rules: "Original work only. No pre-built projects. Judged on innovation, execution, and presentation.",
    contactInfo: "cseclub@cuet.ac.bd",
    registrationLink: "https://example.com/register/cuet-hackathon",
    officialWebsite: "https://example.com/cuet-hackathon",
    status: EventStatus.APPROVED,
    rejectionReason: null,
  },
  {
    name: "UX Research Fundamentals Workshop",
    category: "Workshop",
    organizerName: "Design Society",
    eventDate: daysFromNow(12),
    eventTime: "3:00 PM",
    venue: "Online (Zoom)",
    city: "Online",
    mode: EventMode.ONLINE,
    registrationDeadline: daysFromNow(9),
    registrationFee: "Free",
    prizePool: "N/A",
    eligibility: "Open to all students and early professionals",
    teamSize: "Individual",
    availableSeats: 60,
    certificateInfo: "E-certificate on completion",
    description: "An introductory workshop covering user interviews, usability testing, and synthesizing research into actionable insights.",
    rules: "N/A",
    contactInfo: "hello@designsociety.example",
    registrationLink: "https://example.com/register/ux-workshop",
    officialWebsite: "https://example.com/design-society",
    status: EventStatus.APPROVED,
    rejectionReason: null,
  },
  {
    name: "Inter-University Debate Fest",
    category: "Debate Competition",
    organizerName: "Dhaka Debating Society",
    eventDate: daysFromNow(25),
    eventTime: "10:00 AM",
    venue: "Dhaka University TSC",
    city: "Dhaka",
    mode: EventMode.OFFLINE,
    registrationDeadline: daysFromNow(6),
    registrationFee: "৳500 per team",
    prizePool: "৳80,000 + trophies",
    eligibility: "University students, teams of 2",
    teamSize: "2 members",
    availableSeats: 64,
    certificateInfo: "Certificate for all participating teams",
    description: "A British Parliamentary format debate competition open to all universities across Bangladesh.",
    rules: "BP format. Standard motions released 15 minutes before each round.",
    contactInfo: "dds.contact@example.com",
    registrationLink: "https://example.com/register/debate-fest",
    officialWebsite: "https://example.com/dds",
    status: EventStatus.APPROVED,
    rejectionReason: null,
  },
  {
    name: "Tech Careers Meetup",
    category: "Job Fair",
    organizerName: "SkillBridge Bangladesh",
    eventDate: daysFromNow(35),
    eventTime: "11:00 AM",
    venue: "GEC Convention Center",
    city: "Chattogram",
    mode: EventMode.OFFLINE,
    registrationDeadline: daysFromNow(28),
    registrationFee: "Free",
    prizePool: "N/A",
    eligibility: "Final year students and graduates",
    teamSize: "Individual",
    availableSeats: 300,
    certificateInfo: "N/A",
    description: "Meet recruiters from 15+ tech companies and training institutes. Bring printed copies of your CV.",
    rules: "N/A",
    contactInfo: "info@skillbridge.example",
    registrationLink: "https://example.com/register/tech-careers",
    officialWebsite: "https://example.com/skillbridge",
    status: EventStatus.APPROVED,
    rejectionReason: null,
  },
  {
    name: "National Robotics Olympiad",
    category: "Robotics Competition",
    organizerName: "Robotics Society of Bangladesh",
    eventDate: daysFromNow(45),
    eventTime: "9:00 AM",
    venue: "BUET Central Field",
    city: "Dhaka",
    mode: EventMode.OFFLINE,
    registrationDeadline: daysFromNow(20),
    registrationFee: "৳1000 per team",
    prizePool: "৳300,000",
    eligibility: "School, college, and university students",
    teamSize: "2-5 members",
    availableSeats: 200,
    certificateInfo: "Certificate + medal for finalists",
    description: "Line-following, maze-solving, and combat robotics categories for students of all levels.",
    rules: "Robots must be built by team members. Detailed rulebook available on the official website.",
    contactInfo: "contact@robosociety.example",
    registrationLink: "https://example.com/register/robotics-olympiad",
    officialWebsite: "https://example.com/robosociety",
    status: EventStatus.APPROVED,
    rejectionReason: null,
  },
  {
    name: "AI for Social Good Competition",
    category: "AI Competition",
    organizerName: "AI Club CUET",
    eventDate: daysFromNow(30),
    eventTime: "10:00 AM",
    venue: "Online",
    city: "Online",
    mode: EventMode.ONLINE,
    registrationDeadline: daysFromNow(1),
    registrationFee: "Free",
    prizePool: "৳100,000",
    eligibility: "Open to all, individual or teams up to 4",
    teamSize: "1-4 members",
    availableSeats: null,
    certificateInfo: "E-certificate for all, cash prize for top 3",
    description: "Build an AI/ML solution addressing a real social problem in healthcare, education, or agriculture.",
    rules: "Submissions must include working code, a demo video, and a 1-page writeup.",
    contactInfo: "aiclub@cuet.ac.bd",
    registrationLink: "https://example.com/register/ai-social-good",
    officialWebsite: "https://example.com/aiclub-cuet",
    status: EventStatus.APPROVED,
    rejectionReason: null,
  },
  {
    name: "Business Case Challenge 2026",
    category: "Business Case Competition",
    organizerName: "IBA Business Club",
    eventDate: daysFromNow(40),
    eventTime: "9:30 AM",
    venue: "IBA, University of Dhaka",
    city: "Dhaka",
    mode: EventMode.OFFLINE,
    registrationDeadline: daysFromNow(15),
    registrationFee: "৳800 per team",
    prizePool: "৳200,000",
    eligibility: "Undergraduate students, any discipline",
    teamSize: "3-4 members",
    availableSeats: 150,
    certificateInfo: "Certificate for all participants",
    description: "Solve a real-world business case in 48 hours and pitch your solution to a panel of industry judges.",
    rules: "No external mentorship during the case-solving period.",
    contactInfo: "bizclub@iba-du.example",
    registrationLink: "https://example.com/register/case-challenge",
    officialWebsite: "https://example.com/iba-bizclub",
    status: EventStatus.APPROVED,
    rejectionReason: null,
  },
  {
    name: "Campus Photography Contest — 'Everyday Bangladesh'",
    category: "Photography Contest",
    organizerName: "Lens Club, CUET",
    eventDate: daysFromNow(18),
    eventTime: "N/A (online submission)",
    venue: "Online Submission",
    city: "Online",
    mode: EventMode.ONLINE,
    registrationDeadline: daysFromNow(10),
    registrationFee: "Free",
    prizePool: "৳20,000",
    eligibility: "Open to all",
    teamSize: "Individual",
    availableSeats: null,
    certificateInfo: "Certificate for top 10 entries",
    description: "Submit up to 3 original photographs capturing everyday life in Bangladesh.",
    rules: "No heavy editing/filters. Must be shot within the last 6 months.",
    contactInfo: "lensclub@cuet.ac.bd",
    registrationLink: "https://example.com/register/photo-contest",
    officialWebsite: "https://example.com/lensclub",
    status: EventStatus.APPROVED,
    rejectionReason: null,
  },
  {
    name: "Intra-University Esports Championship",
    category: "Gaming Tournament",
    organizerName: "Gaming Arena Club",
    eventDate: daysFromNow(14),
    eventTime: "5:00 PM",
    venue: "CUET Gaming Lab",
    city: "Chattogram",
    mode: EventMode.OFFLINE,
    registrationDeadline: daysFromNow(5),
    registrationFee: "৳200 per team",
    prizePool: "৳40,000",
    eligibility: "Currently enrolled students only",
    teamSize: "5 members (Valorant), Individual (FIFA)",
    availableSeats: 80,
    certificateInfo: "N/A",
    description: "Valorant 5v5 and FIFA 1v1 brackets. Single elimination format.",
    rules: "Standard competitive ruleset. No custom scripts/macros allowed.",
    contactInfo: "gaming.arena@cuet.ac.bd",
    registrationLink: "https://example.com/register/esports",
    officialWebsite: "https://example.com/gaming-arena",
    status: EventStatus.APPROVED,
    rejectionReason: null,
  },
  {
    name: "Inter-Department Cricket Tournament",
    category: "Sports Tournament",
    organizerName: "Sports Wing, CUET",
    eventDate: daysFromNow(22),
    eventTime: "8:00 AM",
    venue: "CUET Sports Complex",
    city: "Chattogram",
    mode: EventMode.OFFLINE,
    registrationDeadline: daysFromNow(12),
    registrationFee: "৳1500 per team",
    prizePool: "Trophy + ৳25,000",
    eligibility: "Current students, department-wise teams",
    teamSize: "11 + 4 substitutes",
    availableSeats: null,
    certificateInfo: "N/A",
    description: "Annual inter-department T20 cricket tournament.",
    rules: "Standard T20 rules, ICC playing conditions apply.",
    contactInfo: "sports@cuet.ac.bd",
    registrationLink: "https://example.com/register/cricket",
    officialWebsite: "https://example.com/cuet-sports",
    status: EventStatus.APPROVED,
    rejectionReason: null,
  },
  {
    name: "Data Science Bootcamp — Weekend Seminar",
    category: "Seminar",
    organizerName: "TechBridge Training Institute",
    eventDate: daysFromNow(9),
    eventTime: "10:00 AM",
    venue: "Online (Google Meet)",
    city: "Online",
    mode: EventMode.ONLINE,
    registrationDeadline: daysFromNow(2),
    registrationFee: "৳500",
    prizePool: "N/A",
    eligibility: "Open to all, basic Python knowledge recommended",
    teamSize: "Individual",
    availableSeats: 100,
    certificateInfo: "Certificate of participation",
    description: "A weekend seminar covering the fundamentals of data science workflows, from cleaning to visualization.",
    rules: "N/A",
    contactInfo: "info@techbridge.example",
    registrationLink: "https://example.com/register/ds-bootcamp",
    officialWebsite: "https://example.com/techbridge",
    status: EventStatus.APPROVED,
    rejectionReason: null,
  },
  {
    name: "Startup Pitch Night",
    category: "Startup Competition",
    organizerName: "Entrepreneurship Cell, CUET",
    eventDate: daysFromNow(33),
    eventTime: "4:00 PM",
    venue: "CUET Auditorium",
    city: "Chattogram",
    mode: EventMode.OFFLINE,
    registrationDeadline: daysFromNow(18),
    registrationFee: "Free",
    prizePool: "৳500,000 in seed interest + mentorship",
    eligibility: "Early-stage founders and student teams",
    teamSize: "1-5 members",
    availableSeats: 40,
    certificateInfo: "N/A",
    description: "Pitch your startup idea to a panel of investors and industry mentors.",
    rules: "5-minute pitch + 5-minute Q&A per team.",
    contactInfo: "ecell@cuet.ac.bd",
    registrationLink: "https://example.com/register/pitch-night",
    officialWebsite: "https://example.com/ecell-cuet",
    status: EventStatus.APPROVED,
    rejectionReason: null,
  },
  {
    name: "Product Design Sprint",
    category: "Design Contest",
    organizerName: "Design Society",
    eventDate: daysFromNow(27),
    eventTime: "9:00 AM",
    venue: "Online",
    city: "Online",
    mode: EventMode.ONLINE,
    registrationDeadline: daysFromNow(14),
    registrationFee: "Free",
    prizePool: "৳30,000",
    eligibility: "Designers, students, and hobbyists",
    teamSize: "Individual or pairs",
    availableSeats: null,
    certificateInfo: "E-certificate for all participants",
    description: "A 48-hour design sprint to reimagine a everyday app experience, judged on usability and visual craft.",
    rules: "Figma files must be submitted with view access.",
    contactInfo: "hello@designsociety.example",
    registrationLink: "https://example.com/register/design-sprint",
    officialWebsite: "https://example.com/design-society",
    status: EventStatus.APPROVED,
    rejectionReason: null,
  },
  {
    name: "Physics Olympiad — Regional Round",
    category: "Olympiad",
    organizerName: "Bangladesh Physics Olympiad Committee",
    eventDate: daysFromNow(50),
    eventTime: "10:00 AM",
    venue: "Chattogram College",
    city: "Chattogram",
    mode: EventMode.OFFLINE,
    registrationDeadline: daysFromNow(25),
    registrationFee: "৳300",
    prizePool: "Medals + certificates, national round qualification",
    eligibility: "School and college students (classes 9-12)",
    teamSize: "Individual",
    availableSeats: 500,
    certificateInfo: "Certificate for all, medals for top performers",
    description: "Regional qualifying round for the national physics olympiad.",
    rules: "Closed book, 3-hour written exam.",
    contactInfo: "info@bdpho.example",
    registrationLink: "https://example.com/register/physics-olympiad",
    officialWebsite: "https://example.com/bdpho",
    status: EventStatus.APPROVED,
    rejectionReason: null,
  },
  {
    name: "Cultural Night: Utshob 2026",
    category: "Cultural Event",
    organizerName: "Cultural Club, CUET",
    eventDate: daysFromNow(16),
    eventTime: "6:00 PM",
    venue: "CUET Open Air Theatre",
    city: "Chattogram",
    mode: EventMode.OFFLINE,
    registrationDeadline: daysFromNow(11),
    registrationFee: "৳150 (performers), Free (audience)",
    prizePool: "N/A",
    eligibility: "Open to all current students",
    teamSize: "Individual or groups",
    availableSeats: 800,
    certificateInfo: "N/A",
    description: "Annual cultural night featuring music, dance, and drama performances by students.",
    rules: "Performance slots limited to 8 minutes per act.",
    contactInfo: "culturalclub@cuet.ac.bd",
    registrationLink: "https://example.com/register/utshob",
    officialWebsite: "https://example.com/cuet-cultural",
    status: EventStatus.APPROVED,
    rejectionReason: null,
  },
  {
    name: "Career Fair: Engineering & Tech 2026",
    category: "Career Fair",
    organizerName: "Career Development Center, CUET",
    eventDate: daysFromNow(38),
    eventTime: "10:00 AM",
    venue: "CUET Gymnasium",
    city: "Chattogram",
    mode: EventMode.OFFLINE,
    registrationDeadline: daysFromNow(30),
    registrationFee: "Free",
    prizePool: "N/A",
    eligibility: "Final year students and alumni",
    teamSize: "Individual",
    availableSeats: 1000,
    certificateInfo: "N/A",
    description: "Connect with 30+ engineering and tech employers hiring for full-time and internship roles.",
    rules: "N/A",
    contactInfo: "cdc@cuet.ac.bd",
    registrationLink: "https://example.com/register/career-fair",
    officialWebsite: "https://example.com/cuet-cdc",
    status: EventStatus.APPROVED,
    rejectionReason: null,
  },
  {
    name: "Intro to Cloud Computing Webinar",
    category: "Webinar",
    organizerName: "Cloud Native Bangladesh",
    eventDate: daysFromNow(7),
    eventTime: "8:00 PM",
    venue: "Online (YouTube Live)",
    city: "Online",
    mode: EventMode.ONLINE,
    registrationDeadline: daysFromNow(6),
    registrationFee: "Free",
    prizePool: "N/A",
    eligibility: "Open to all",
    teamSize: "Individual",
    availableSeats: null,
    certificateInfo: "N/A",
    description: "An introductory session on cloud fundamentals: compute, storage, and networking basics.",
    rules: "N/A",
    contactInfo: "hello@cloudnativebd.example",
    registrationLink: "https://example.com/register/cloud-webinar",
    officialWebsite: "https://example.com/cloudnativebd",
    status: EventStatus.APPROVED,
    rejectionReason: null,
  },
  {
    name: "Junior Coding Olympiad (School Level)",
    category: "Programming Contest",
    organizerName: "Code for Bangladesh",
    eventDate: daysFromNow(42),
    eventTime: "9:00 AM",
    venue: "Online (Codeforces Gym)",
    city: "Online",
    mode: EventMode.ONLINE,
    registrationDeadline: daysFromNow(4),
    registrationFee: "Free",
    prizePool: "৳50,000 + prizes",
    eligibility: "School students, classes 6-10",
    teamSize: "Individual",
    availableSeats: null,
    certificateInfo: "E-certificate for all, medals for top 20",
    description: "A beginner-friendly programming contest introducing school students to competitive coding.",
    rules: "Standard ICPC-style rules, simplified problem set.",
    contactInfo: "contact@codeforbd.example",
    registrationLink: "https://example.com/register/junior-olympiad",
    officialWebsite: "https://example.com/codeforbd",
    status: EventStatus.APPROVED,
    rejectionReason: null,
  },
  {
    name: "Freelancing Bootcamp for Beginners",
    category: "Workshop",
    organizerName: "SkillBridge Bangladesh",
    eventDate: daysFromNow(19),
    eventTime: "2:00 PM",
    venue: "Online",
    city: "Online",
    mode: EventMode.ONLINE,
    registrationDeadline: daysFromNow(13),
    registrationFee: "৳300",
    prizePool: "N/A",
    eligibility: "Open to all",
    teamSize: "Individual",
    availableSeats: 200,
    certificateInfo: "Certificate on completion",
    description: "A hands-on bootcamp on getting started with freelancing on international platforms.",
    rules: "N/A",
    contactInfo: "info@skillbridge.example",
    registrationLink: "https://example.com/register/freelancing-bootcamp",
    officialWebsite: "https://example.com/skillbridge",
    status: EventStatus.PENDING,
    rejectionReason: null,
  },
  {
    name: "Mega Prize Giveaway Contest",
    category: "Gaming Tournament",
    organizerName: "QuickWin Promotions",
    eventDate: daysFromNow(5),
    eventTime: "TBA",
    venue: "TBA",
    city: "Online",
    mode: EventMode.ONLINE,
    registrationDeadline: daysFromNow(2),
    registrationFee: "Free",
    prizePool: "Unverified claim of ৳1,000,000",
    eligibility: "Unclear",
    teamSize: "Individual",
    availableSeats: null,
    certificateInfo: "N/A",
    description: "Suspicious submission with vague details and no verifiable organizer identity.",
    rules: "N/A",
    contactInfo: "N/A",
    registrationLink: "https://example.com/suspicious-link",
    officialWebsite: "",
    status: EventStatus.REJECTED,
    rejectionReason: "Organizer identity could not be verified and event details are incomplete/suspicious.",
  },
];

async function main() {
  console.log('Seeding database...');

  // 1. Clean existing data in reverse order of foreign keys
  await prisma.savedEvent.deleteMany();
  await prisma.event.deleteMany();
  await prisma.category.deleteMany();
  await prisma.user.deleteMany();

  // 2. Hash default password for seeded users
  const passwordHash = await bcrypt.hash('password123', 10);

  // 3. Seed Users
  console.log('Seeding users...');
  const seededUsers = [];
  for (const u of mockUsersData) {
    const user = await prisma.user.create({
      data: {
        id: u.id,
        name: u.name,
        email: u.email,
        passwordHash,
        role: u.role,
        verified: u.verified,
        status: u.status,
        createdAt: u.createdAt,
      },
    });
    seededUsers.push(user);
  }

  // Seed Admin user
  const adminUser = await prisma.user.create({
    data: {
      name: "System Admin",
      email: "admin@khoj.dev",
      passwordHash,
      role: Role.ADMIN,
      verified: true,
      status: UserStatus.ACTIVE,
    },
  });
  seededUsers.push(adminUser);
  console.log(`Seeded ${seededUsers.length} users (including 1 Admin).`);

  // 4. Seed Categories
  console.log('Seeding categories...');
  const uniqueCategoryNames = Array.from(
    new Set(mockEventsRaw.map((e) => e.category))
  ).sort();

  const categoryMap = new Map<string, string>();
  for (const name of uniqueCategoryNames) {
    const category = await prisma.category.create({
      data: { name },
    });
    categoryMap.set(name, category.id);
  }
  console.log(`Seeded ${categoryMap.size} categories.`);

  // 5. Seed Events
  console.log('Seeding events...');
  const organizers = seededUsers.filter((u) => u.role === Role.ORGANIZER);
  const defaultOrganizerId = organizers[0]?.id || adminUser.id;

  // Map organizers by index or name
  let organizerIndex = 0;
  for (const evt of mockEventsRaw) {
    const categoryId = categoryMap.get(evt.category);
    if (!categoryId) {
      throw new Error(`Category ${evt.category} not found`);
    }

    // Pick an organizer user for the event
    const organizer = organizers[organizerIndex % organizers.length] || adminUser;
    organizerIndex++;

    await prisma.event.create({
      data: {
        name: evt.name,
        categoryId: categoryId,
        organizerId: organizer.id,
        eventDate: evt.eventDate,
        eventTime: evt.eventTime,
        venue: evt.venue,
        city: evt.city,
        mode: evt.mode,
        registrationDeadline: evt.registrationDeadline,
        registrationFee: evt.registrationFee,
        prizePool: evt.prizePool,
        eligibility: evt.eligibility,
        teamSize: evt.teamSize,
        availableSeats: evt.availableSeats,
        certificateInfo: evt.certificateInfo,
        description: evt.description,
        rules: evt.rules,
        contactInfo: evt.contactInfo,
        registrationLink: evt.registrationLink,
        officialWebsite: evt.officialWebsite,
        bannerImageUrl: null,
        status: evt.status,
        rejectionReason: evt.rejectionReason,
      },
    });
  }

  console.log(`Seeded ${mockEventsRaw.length} events.`);
  console.log('Database seeding completed successfully!');
}

main()
  .catch((e) => {
    console.error('Error during seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
