import { KhojEvent } from "./types";

// Dates are relative to "today" so deadline-urgency styling stays realistic
// no matter when this mock data is viewed during development.
const today = new Date();
function daysFromNow(days: number): string {
  const d = new Date(today);
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

export const mockEvents: KhojEvent[] = [
  {
    id: "evt-001",
    name: "CUET Innovation Hackathon 2026",
    category: "Hackathon",
    organizerName: "CSE Club, CUET",
    organizerVerified: true,
    eventDate: daysFromNow(20),
    eventTime: "9:00 AM",
    venue: "CUET Auditorium",
    city: "Chattogram",
    mode: "offline",
    registrationDeadline: daysFromNow(3),
    registrationFee: "৳300 per team",
    prizePool: "৳150,000",
    eligibility: "Undergraduate students, teams of 3-4",
    teamSize: "3-4 members",
    availableSeats: 120,
    certificateInfo: "E-certificate for all participants, printed certificate for winners",
    description:
      "A 24-hour hackathon focused on building solutions for campus and civic problems using any tech stack.",
    rules: "Original work only. No pre-built projects. Judged on innovation, execution, and presentation.",
    contactInfo: "cseclub@cuet.ac.bd",
    registrationLink: "https://example.com/register/cuet-hackathon",
    officialWebsite: "https://example.com/cuet-hackathon",
    bannerColor: "primary",
    status: "approved",
    saved: true,
  },
  {
    id: "evt-002",
    name: "UX Research Fundamentals Workshop",
    category: "Workshop",
    organizerName: "Design Society",
    organizerVerified: true,
    eventDate: daysFromNow(12),
    eventTime: "3:00 PM",
    venue: "Online (Zoom)",
    city: "Online",
    mode: "online",
    registrationDeadline: daysFromNow(9),
    registrationFee: "Free",
    prizePool: "N/A",
    eligibility: "Open to all students and early professionals",
    teamSize: "Individual",
    availableSeats: 60,
    certificateInfo: "E-certificate on completion",
    description:
      "An introductory workshop covering user interviews, usability testing, and synthesizing research into actionable insights.",
    rules: "N/A",
    contactInfo: "hello@designsociety.example",
    registrationLink: "https://example.com/register/ux-workshop",
    officialWebsite: "https://example.com/design-society",
    bannerColor: "success",
    status: "approved",
  },
  {
    id: "evt-003",
    name: "Inter-University Debate Fest",
    category: "Debate Competition",
    organizerName: "Dhaka Debating Society",
    organizerVerified: true,
    eventDate: daysFromNow(25),
    eventTime: "10:00 AM",
    venue: "Dhaka University TSC",
    city: "Dhaka",
    mode: "offline",
    registrationDeadline: daysFromNow(6),
    registrationFee: "৳500 per team",
    prizePool: "৳80,000 + trophies",
    eligibility: "University students, teams of 2",
    teamSize: "2 members",
    availableSeats: 64,
    certificateInfo: "Certificate for all participating teams",
    description:
      "A British Parliamentary format debate competition open to all universities across Bangladesh.",
    rules: "BP format. Standard motions released 15 minutes before each round.",
    contactInfo: "dds.contact@example.com",
    registrationLink: "https://example.com/register/debate-fest",
    officialWebsite: "https://example.com/dds",
    bannerColor: "error",
    status: "approved",
  },
  {
    id: "evt-004",
    name: "Tech Careers Meetup",
    category: "Job Fair",
    organizerName: "SkillBridge Bangladesh",
    organizerVerified: false,
    eventDate: daysFromNow(35),
    eventTime: "11:00 AM",
    venue: "GEC Convention Center",
    city: "Chattogram",
    mode: "offline",
    registrationDeadline: daysFromNow(28),
    registrationFee: "Free",
    prizePool: "N/A",
    eligibility: "Final year students and graduates",
    teamSize: "Individual",
    availableSeats: 300,
    certificateInfo: "N/A",
    description:
      "Meet recruiters from 15+ tech companies and training institutes. Bring printed copies of your CV.",
    rules: "N/A",
    contactInfo: "info@skillbridge.example",
    registrationLink: "https://example.com/register/tech-careers",
    officialWebsite: "https://example.com/skillbridge",
    bannerColor: "primary",
    status: "approved",
  },
  {
    id: "evt-005",
    name: "National Robotics Olympiad",
    category: "Robotics Competition",
    organizerName: "Robotics Society of Bangladesh",
    organizerVerified: true,
    eventDate: daysFromNow(45),
    eventTime: "9:00 AM",
    venue: "BUET Central Field",
    city: "Dhaka",
    mode: "offline",
    registrationDeadline: daysFromNow(20),
    registrationFee: "৳1000 per team",
    prizePool: "৳300,000",
    eligibility: "School, college, and university students",
    teamSize: "2-5 members",
    availableSeats: 200,
    certificateInfo: "Certificate + medal for finalists",
    description:
      "Line-following, maze-solving, and combat robotics categories for students of all levels.",
    rules: "Robots must be built by team members. Detailed rulebook available on the official website.",
    contactInfo: "contact@robosociety.example",
    registrationLink: "https://example.com/register/robotics-olympiad",
    officialWebsite: "https://example.com/robosociety",
    bannerColor: "warning",
    status: "approved",
  },
  {
    id: "evt-006",
    name: "AI for Social Good Competition",
    category: "AI Competition",
    organizerName: "AI Club CUET",
    organizerVerified: true,
    eventDate: daysFromNow(30),
    eventTime: "10:00 AM",
    venue: "Online",
    city: "Online",
    mode: "online",
    registrationDeadline: daysFromNow(1),
    registrationFee: "Free",
    prizePool: "৳100,000",
    eligibility: "Open to all, individual or teams up to 4",
    teamSize: "1-4 members",
    availableSeats: null,
    certificateInfo: "E-certificate for all, cash prize for top 3",
    description:
      "Build an AI/ML solution addressing a real social problem in healthcare, education, or agriculture.",
    rules: "Submissions must include working code, a demo video, and a 1-page writeup.",
    contactInfo: "aiclub@cuet.ac.bd",
    registrationLink: "https://example.com/register/ai-social-good",
    officialWebsite: "https://example.com/aiclub-cuet",
    bannerColor: "primary",
    status: "approved",
  },
  {
    id: "evt-007",
    name: "Business Case Challenge 2026",
    category: "Business Case Competition",
    organizerName: "IBA Business Club",
    organizerVerified: true,
    eventDate: daysFromNow(40),
    eventTime: "9:30 AM",
    venue: "IBA, University of Dhaka",
    city: "Dhaka",
    mode: "offline",
    registrationDeadline: daysFromNow(15),
    registrationFee: "৳800 per team",
    prizePool: "৳200,000",
    eligibility: "Undergraduate students, any discipline",
    teamSize: "3-4 members",
    availableSeats: 150,
    certificateInfo: "Certificate for all participants",
    description:
      "Solve a real-world business case in 48 hours and pitch your solution to a panel of industry judges.",
    rules: "No external mentorship during the case-solving period.",
    contactInfo: "bizclub@iba-du.example",
    registrationLink: "https://example.com/register/case-challenge",
    officialWebsite: "https://example.com/iba-bizclub",
    bannerColor: "success",
    status: "approved",
  },
  {
    id: "evt-008",
    name: "Campus Photography Contest — 'Everyday Bangladesh'",
    category: "Photography Contest",
    organizerName: "Lens Club, CUET",
    organizerVerified: false,
    eventDate: daysFromNow(18),
    eventTime: "N/A (online submission)",
    venue: "Online Submission",
    city: "Online",
    mode: "online",
    registrationDeadline: daysFromNow(10),
    registrationFee: "Free",
    prizePool: "৳20,000",
    eligibility: "Open to all",
    teamSize: "Individual",
    availableSeats: null,
    certificateInfo: "Certificate for top 10 entries",
    description:
      "Submit up to 3 original photographs capturing everyday life in Bangladesh.",
    rules: "No heavy editing/filters. Must be shot within the last 6 months.",
    contactInfo: "lensclub@cuet.ac.bd",
    registrationLink: "https://example.com/register/photo-contest",
    officialWebsite: "https://example.com/lensclub",
    bannerColor: "warning",
    status: "approved",
  },
  {
    id: "evt-009",
    name: "Intra-University Esports Championship",
    category: "Gaming Tournament",
    organizerName: "Gaming Arena Club",
    organizerVerified: false,
    eventDate: daysFromNow(14),
    eventTime: "5:00 PM",
    venue: "CUET Gaming Lab",
    city: "Chattogram",
    mode: "offline",
    registrationDeadline: daysFromNow(5),
    registrationFee: "৳200 per team",
    prizePool: "৳40,000",
    eligibility: "Currently enrolled students only",
    teamSize: "5 members (Valorant), Individual (FIFA)",
    availableSeats: 80,
    certificateInfo: "N/A",
    description: "Valorant 5v5 and FIFA 1v1 brackets. Single elimination format.",
    rules: "Standard competitive ruleset. No custom scripts/macros allowed.",
    contactInfo: "gaming.arena@cuet.ac.bd",
    registrationLink: "https://example.com/register/esports",
    officialWebsite: "https://example.com/gaming-arena",
    bannerColor: "error",
    status: "approved",
  },
  {
    id: "evt-010",
    name: "Inter-Department Cricket Tournament",
    category: "Sports Tournament",
    organizerName: "Sports Wing, CUET",
    organizerVerified: true,
    eventDate: daysFromNow(22),
    eventTime: "8:00 AM",
    venue: "CUET Sports Complex",
    city: "Chattogram",
    mode: "offline",
    registrationDeadline: daysFromNow(12),
    registrationFee: "৳1500 per team",
    prizePool: "Trophy + ৳25,000",
    eligibility: "Current students, department-wise teams",
    teamSize: "11 + 4 substitutes",
    availableSeats: null,
    certificateInfo: "N/A",
    description: "Annual inter-department T20 cricket tournament.",
    rules: "Standard T20 rules, ICC playing conditions apply.",
    contactInfo: "sports@cuet.ac.bd",
    registrationLink: "https://example.com/register/cricket",
    officialWebsite: "https://example.com/cuet-sports",
    bannerColor: "success",
    status: "approved",
  },
  {
    id: "evt-011",
    name: "Data Science Bootcamp — Weekend Seminar",
    category: "Seminar",
    organizerName: "TechBridge Training Institute",
    organizerVerified: true,
    eventDate: daysFromNow(9),
    eventTime: "10:00 AM",
    venue: "Online (Google Meet)",
    city: "Online",
    mode: "online",
    registrationDeadline: daysFromNow(2),
    registrationFee: "৳500",
    prizePool: "N/A",
    eligibility: "Open to all, basic Python knowledge recommended",
    teamSize: "Individual",
    availableSeats: 100,
    certificateInfo: "Certificate of participation",
    description:
      "A weekend seminar covering the fundamentals of data science workflows, from cleaning to visualization.",
    rules: "N/A",
    contactInfo: "info@techbridge.example",
    registrationLink: "https://example.com/register/ds-bootcamp",
    officialWebsite: "https://example.com/techbridge",
    bannerColor: "primary",
    status: "approved",
  },
  {
    id: "evt-012",
    name: "Startup Pitch Night",
    category: "Startup Competition",
    organizerName: "Entrepreneurship Cell, CUET",
    organizerVerified: true,
    eventDate: daysFromNow(33),
    eventTime: "4:00 PM",
    venue: "CUET Auditorium",
    city: "Chattogram",
    mode: "offline",
    registrationDeadline: daysFromNow(18),
    registrationFee: "Free",
    prizePool: "৳500,000 in seed interest + mentorship",
    eligibility: "Early-stage founders and student teams",
    teamSize: "1-5 members",
    availableSeats: 40,
    certificateInfo: "N/A",
    description: "Pitch your startup idea to a panel of investors and industry mentors.",
    rules: "5-minute pitch + 5-minute Q&A per team.",
    contactInfo: "ecell@cuet.ac.bd",
    registrationLink: "https://example.com/register/pitch-night",
    officialWebsite: "https://example.com/ecell-cuet",
    bannerColor: "warning",
    status: "approved",
  },
  {
    id: "evt-013",
    name: "Product Design Sprint",
    category: "Design Contest",
    organizerName: "Design Society",
    organizerVerified: true,
    eventDate: daysFromNow(27),
    eventTime: "9:00 AM",
    venue: "Online",
    city: "Online",
    mode: "online",
    registrationDeadline: daysFromNow(14),
    registrationFee: "Free",
    prizePool: "৳30,000",
    eligibility: "Designers, students, and hobbyists",
    teamSize: "Individual or pairs",
    availableSeats: null,
    certificateInfo: "E-certificate for all participants",
    description:
      "A 48-hour design sprint to reimagine a everyday app experience, judged on usability and visual craft.",
    rules: "Figma files must be submitted with view access.",
    contactInfo: "hello@designsociety.example",
    registrationLink: "https://example.com/register/design-sprint",
    officialWebsite: "https://example.com/design-society",
    bannerColor: "success",
    status: "approved",
  },
  {
    id: "evt-014",
    name: "Physics Olympiad — Regional Round",
    category: "Olympiad",
    organizerName: "Bangladesh Physics Olympiad Committee",
    organizerVerified: true,
    eventDate: daysFromNow(50),
    eventTime: "10:00 AM",
    venue: "Chattogram College",
    city: "Chattogram",
    mode: "offline",
    registrationDeadline: daysFromNow(25),
    registrationFee: "৳300",
    prizePool: "Medals + certificates, national round qualification",
    eligibility: "School and college students (classes 9-12)",
    teamSize: "Individual",
    availableSeats: 500,
    certificateInfo: "Certificate for all, medals for top performers",
    description: "Regional qualifying round for the national physics olympiad.",
    rules: "Closed book, 3-hour written exam.",
    contactInfo: "info@bdpho.example",
    registrationLink: "https://example.com/register/physics-olympiad",
    officialWebsite: "https://example.com/bdpho",
    bannerColor: "primary",
    status: "approved",
  },
  {
    id: "evt-015",
    name: "Cultural Night: Utshob 2026",
    category: "Cultural Event",
    organizerName: "Cultural Club, CUET",
    organizerVerified: true,
    eventDate: daysFromNow(16),
    eventTime: "6:00 PM",
    venue: "CUET Open Air Theatre",
    city: "Chattogram",
    mode: "offline",
    registrationDeadline: daysFromNow(11),
    registrationFee: "৳150 (performers), Free (audience)",
    prizePool: "N/A",
    eligibility: "Open to all current students",
    teamSize: "Individual or groups",
    availableSeats: 800,
    certificateInfo: "N/A",
    description: "Annual cultural night featuring music, dance, and drama performances by students.",
    rules: "Performance slots limited to 8 minutes per act.",
    contactInfo: "culturalclub@cuet.ac.bd",
    registrationLink: "https://example.com/register/utshob",
    officialWebsite: "https://example.com/cuet-cultural",
    bannerColor: "error",
    status: "approved",
  },
  {
    id: "evt-016",
    name: "Career Fair: Engineering & Tech 2026",
    category: "Career Fair",
    organizerName: "Career Development Center, CUET",
    organizerVerified: true,
    eventDate: daysFromNow(38),
    eventTime: "10:00 AM",
    venue: "CUET Gymnasium",
    city: "Chattogram",
    mode: "offline",
    registrationDeadline: daysFromNow(30),
    registrationFee: "Free",
    prizePool: "N/A",
    eligibility: "Final year students and alumni",
    teamSize: "Individual",
    availableSeats: 1000,
    certificateInfo: "N/A",
    description: "Connect with 30+ engineering and tech employers hiring for full-time and internship roles.",
    rules: "N/A",
    contactInfo: "cdc@cuet.ac.bd",
    registrationLink: "https://example.com/register/career-fair",
    officialWebsite: "https://example.com/cuet-cdc",
    bannerColor: "primary",
    status: "approved",
  },
  {
    id: "evt-017",
    name: "Intro to Cloud Computing Webinar",
    category: "Webinar",
    organizerName: "Cloud Native Bangladesh",
    organizerVerified: false,
    eventDate: daysFromNow(7),
    eventTime: "8:00 PM",
    venue: "Online (YouTube Live)",
    city: "Online",
    mode: "online",
    registrationDeadline: daysFromNow(6),
    registrationFee: "Free",
    prizePool: "N/A",
    eligibility: "Open to all",
    teamSize: "Individual",
    availableSeats: null,
    certificateInfo: "N/A",
    description: "An introductory session on cloud fundamentals: compute, storage, and networking basics.",
    rules: "N/A",
    contactInfo: "hello@cloudnativebd.example",
    registrationLink: "https://example.com/register/cloud-webinar",
    officialWebsite: "https://example.com/cloudnativebd",
    bannerColor: "success",
    status: "approved",
  },
  {
    id: "evt-018",
    name: "Junior Coding Olympiad (School Level)",
    category: "Programming Contest",
    organizerName: "Code for Bangladesh",
    organizerVerified: true,
    eventDate: daysFromNow(42),
    eventTime: "9:00 AM",
    venue: "Online (Codeforces Gym)",
    city: "Online",
    mode: "online",
    registrationDeadline: daysFromNow(4),
    registrationFee: "Free",
    prizePool: "৳50,000 + prizes",
    eligibility: "School students, classes 6-10",
    teamSize: "Individual",
    availableSeats: null,
    certificateInfo: "E-certificate for all, medals for top 20",
    description: "A beginner-friendly programming contest introducing school students to competitive coding.",
    rules: "Standard ICPC-style rules, simplified problem set.",
    contactInfo: "contact@codeforbd.example",
    registrationLink: "https://example.com/register/junior-olympiad",
    officialWebsite: "https://example.com/codeforbd",
    bannerColor: "warning",
    status: "approved",
  },
  // A couple of pending/rejected examples so Organizer/Admin screens have data to show later.
  {
    id: "evt-019",
    name: "Freelancing Bootcamp for Beginners",
    category: "Workshop",
    organizerName: "SkillBridge Bangladesh",
    organizerVerified: false,
    eventDate: daysFromNow(19),
    eventTime: "2:00 PM",
    venue: "Online",
    city: "Online",
    mode: "online",
    registrationDeadline: daysFromNow(13),
    registrationFee: "৳300",
    prizePool: "N/A",
    eligibility: "Open to all",
    teamSize: "Individual",
    availableSeats: 200,
    certificateInfo: "Certificate on completion",
    description: "A hands-on bootcamp on getting started with freelancing on international platforms.",
    rules: "N/A",
    contactInfo: "info@skillbridge.example",
    registrationLink: "https://example.com/register/freelancing-bootcamp",
    officialWebsite: "https://example.com/skillbridge",
    bannerColor: "primary",
    status: "pending",
  },
  {
    id: "evt-020",
    name: "Mega Prize Giveaway Contest",
    category: "Gaming Tournament",
    organizerName: "QuickWin Promotions",
    organizerVerified: false,
    eventDate: daysFromNow(5),
    eventTime: "TBA",
    venue: "TBA",
    city: "Online",
    mode: "online",
    registrationDeadline: daysFromNow(2),
    registrationFee: "Free",
    prizePool: "Unverified claim of ৳1,000,000",
    eligibility: "Unclear",
    teamSize: "Individual",
    availableSeats: null,
    certificateInfo: "N/A",
    description: "Suspicious submission with vague details and no verifiable organizer identity.",
    rules: "N/A",
    contactInfo: "N/A",
    registrationLink: "https://example.com/suspicious-link",
    officialWebsite: "",
    bannerColor: "error",
    status: "rejected",
    rejectionReason: "Organizer identity could not be verified and event details are incomplete/suspicious.",
  },
];
